// DocsData.jsx — journal catalog used by DocsPage.
// Content supplied by product team (April 2026).

const JOURNAL_GROUPS = [
  {
    id: "econ-tier-1",
    name: "Economics – Tier 1",
    description: "Top-tier economics, econometrics, and general science journals. Includes flagship publications like the American Economic Review, Econometrica, Quarterly Journal of Economics, and high-impact multidisciplinary outlets such as Nature and Science.",
    journals: [
      "American Economic Journal: Applied Economics",
      "American Economic Journal: Economic Policy",
      "American Economic Journal: Macroeconomics",
      "American Economic Review",
      "American Journal of Agricultural Economics",
      "Annals of Statistics",
      "Asian Development Review",
      "Ecological Economics",
      "Econometrica",
      "Economic Journal",
      "Energy Economics",
      "European Economic Review",
      "Gender and Society",
      "IEEE Transactions on Geoscience and Remote Sensing",
      "Industrial and Corporate Change",
      "International Journal of Production Economics",
      "International Journal of Urban and Regional Research",
      "Journal of Accounting and Economics",
      "Journal of Banking and Finance",
      "Journal of Consumer Research",
      "Journal of Development Economics",
      "Journal of Econometrics",
      "Journal of Economic Behavior and Organization",
      "Journal of Economic Literature",
      "Journal of Economic Perspectives",
      "Journal of Environmental Economics and Management",
      "Journal of Finance",
      "Journal of Financial and Quantitative Analysis",
      "Journal of Financial Economics",
      "Journal of Human Resources",
      "Journal of International Economics",
      "Journal of Labor Economics",
      "Journal of Management",
      "Journal of Monetary Economics",
      "Journal of Money, Credit and Banking",
      "Journal of Political Economy",
      "Journal of Public Economics",
      "Journal of the American Statistical Association",
      "Journal of the European Economic Association",
      "Journal of the Royal Society Interface",
      "Journal of the Royal Statistical Society: Series A (Statistics in Society)",
      "Journal of the Royal Statistical Society: Series B (Statistical Methodology)",
      "Journal of the Royal Statistical Society: Series C (Applied Statistics)",
      "Journal of Urban Economics",
      "Management Science",
      "Nature",
      "PLoS ONE",
      "Proceedings of the National Academy of Sciences of the United States of America",
      "Quarterly Journal of Economics",
      "RAND Journal of Economics",
      "Remote Sensing of Environment",
      "Resources, Conservation and Recycling",
      "Review of Economic Studies",
      "Review of Economics and Statistics",
      "Review of Financial Studies",
      "Science",
      "Scientific Reports",
      "Social Indicators Research",
      "Statistical Science",
      "World Development",
    ],
  },
  {
    id: "econ-tier-2",
    name: "Economics – Tier 2",
    description: "Broader economics coverage spanning development, regional, agricultural, environmental, and applied economics. Also includes specialized statistics, finance, and policy journals as well as area-studies outlets for Asia, Europe, and Latin America.",
    journals: [
      "Accounting and Finance","AgBioForum","Agribusiness","Agricultural Economics",
      "Agroecology and Sustainable Food Systems","American Statistician",
      "Annals of Applied Statistics","Annual Review of Economics","Applied Economic Perspectives and Policy",
      "Applied Economics","Applied Economics Letters","Asia and the Pacific Policy Studies",
      "Asia Pacific Journal of Management","Asia Pacific Viewpoint","Asian Economic Journal",
      "Asian Economic Papers","Asian Economic Policy Review","Asian-Pacific Economic Literature",
      "Australian and New Zealand Journal of Statistics","Australian Journal of Agricultural and Resource Economics",
      "B.E. Journal of Economic Analysis and Policy","Biometrical Journal","Biometrika","Biostatistics",
      "Brookings Papers on Economic Activity","Cambridge Journal of Economics",
      "Cambridge Journal of Regions, Economy and Society","Canadian Journal of Economics",
      "Canadian Journal of Statistics","China and World Economy","China Economic Review",
      "China Quarterly","Cities","Communist and Post-Communist Studies","Community Development Journal",
      "Computational Economics","Computational Statistics","Conflict Management and Peace Science",
      "Contemporary Economic Policy","Corporate Social Responsibility and Environmental Management",
      "Development and Change","Development in Practice","Development Policy Review",
      "Econometric Reviews","Econometric Theory","Economic and Political Weekly",
      "Economic Development and Cultural Change","Economic Development Quarterly","Economic Geography",
      "Economic History Review","Economic Inquiry","Economic Modelling","Economic Policy",
      "Economic Record","Economic Systems Research","Economic Theory","Economica",
      "Economics and Politics","Economics Letters","Economics of Education Review",
      "Economics of Transition","Economy and Society","Electronic Journal of Statistics",
      "Emerging Markets Finance and Trade","Emerging Markets Review","Empirical Economics",
      "Energy Journal","Environment and Development Economics","Environment, Development and Sustainability",
      "Environmental and Ecological Statistics","Environmental and Resource Economics","Environmental Hazards",
      "Eurasian Geography and Economics","Europe-Asia Studies","European Financial Management",
      "European Journal of Development Research","European Journal of Health Economics",
      "European Journal of Political Economy","European Review of Agricultural Economics",
      "Evaluation","Experimental Economics","Explorations in Economic History","Feminist Economics",
      "Finance and Stochastics","Financial Analysts Journal","Financial Management","Financial Review",
      "Fiscal Studies","Food Policy","Food Security","Forest Policy and Economics","Futures",
      "Games and Economic Behavior","Gender and Development","Gender, Technology and Development",
      "Gender, Work and Organization","Housing Policy Debate","Housing, Theory and Society","IDS Bulletin",
      "IEEE Geoscience and Remote Sensing Letters",
      "IEEE Journal of Selected Topics in Applied Earth Observations and Remote Sensing",
      "Industrial and Labor Relations Review","Information Economics and Policy",
      "Insurance: Mathematics and Economics","International Economic Review","International Finance",
      "International Journal of Consumer Studies","International Journal of Educational Development",
      "International Journal of Finance and Economics","International Journal of Game Theory",
      "International Journal of Industrial Organization","International Journal of Market Research",
      "International Journal of Social Economics","International Journal of Water Resources Development",
      "International Review of Economics and Finance","International Review of Financial Analysis",
      "International Review of Law and Economics","International Statistical Review",
      "International Tax and Public Finance","Internet Research",
      "ISPRS International Journal of Geo-Information","ISPRS Journal of Photogrammetry and Remote Sensing",
      "Japan and the World Economy","Journal of Accounting, Auditing and Finance",
      "Journal of Advanced Transportation","Journal of Agricultural and Resource Economics",
      "Journal of Agricultural, Biological, and Environmental Statistics","Journal of Applied Econometrics",
      "Journal of Applied Economics","Journal of Applied Statistics","Journal of Asian Economics",
      "Journal of Behavioral and Experimental Economics","Journal of Big Data",
      "Journal of Business and Economic Statistics","Journal of Business Finance and Accounting",
      "Journal of Classification","Journal of Common Market Studies","Journal of Comparative Economics",
      "Journal of Consumer Affairs","Journal of Consumer Culture","Journal of Consumer Policy",
      "Journal of Contemporary China","Journal of Corporate Finance","Journal of Cultural Economics",
      "Journal of Cultural Heritage","Journal of Derivatives","Journal of Development Studies",
      "Journal of Economic Dynamics and Control","Journal of Economic Education","Journal of Economic Geography",
      "Journal of Economic Growth","Journal of Economic History","Journal of Economic Issues",
      "Journal of Economic Psychology","Journal of Economic Studies","Journal of Economic Surveys",
      "Journal of Economic Theory","Journal of Economics and Business","Journal of Economics and Management Strategy",
      "Journal of Empirical Finance","Journal of Environment and Development","Journal of Evolutionary Economics",
      "Journal of Family and Economic Issues","Journal of Financial Intermediation",
      "Journal of Financial Markets","Journal of Financial Research","Journal of Financial Services Research",
      "Journal of Financial Stability","Journal of Forecasting","Journal of Futures Markets",
      "Journal of Housing Economics","Journal of Industrial Ecology","Journal of Industrial Economics",
      "Journal of International Development","Journal of International Economic Law",
      "Journal of International Financial Markets, Institutions and Money","Journal of International Management",
      "Journal of International Money and Finance","Journal of Law and Economics",
      "Journal of Law, Economics, and Organization","Journal of Macroeconomics",
      "Journal of Mathematical Economics","Journal of Mixed Methods Research",
      "Journal of Multinational Financial Management","Journal of Multivariate Analysis",
      "Journal of Official Statistics","Journal of Planning Education and Research",
      "Journal of Policy Modeling","Journal of Population Economics","Journal of Portfolio Management",
      "Journal of Post Keynesian Economics","Journal of Productivity Analysis",
      "Journal of Real Estate Finance and Economics","Journal of Regional Science",
      "Journal of Regulatory Economics","Journal of Risk and Insurance","Journal of Risk and Uncertainty",
      "Journal of Rural Studies","Journal of Sports Economics","Journal of Statistical Computation and Simulation",
      "Journal of Statistical Mechanics: Theory and Experiment","Journal of Statistics Education",
      "Journal of Supply Chain Management","Journal of the American Planning Association",
      "Journal of the Japanese and International Economies",
      "Journal of the Urban Planning and Development Division, ASCE","Journal of Time Series Analysis",
      "Journal of Transport Economics and Policy","Journal of Women, Politics and Policy",
      "Journal of Workplace Learning","Judgment and Decision Making","Kyklos",
      "Labour Economics","Lancet","Lancet Global Health","Lancet Infectious Diseases","Lancet Neurology",
      "Lancet Oncology","Lancet Psychiatry","Lancet Public Health","Lancet Regional Health - Americas",
      "Lancet Regional Health - Europe","Lancet Regional Health - Southeast Asia",
      "Lancet Regional Health - Western Pacific","Land Degradation and Development","Land Economics",
      "Local Government Studies","Long Range Planning","Macroeconomic Dynamics","Malaria Journal",
      "Manchester School","Marine Policy","Marine Resource Economics","Maritime Economics and Logistics",
      "Maternal & Child Nutrition","Mathematical Finance","Mathematical Population Studies",
      "Metrika","Metroeconomica","Mountain Research and Development","National Tax Journal",
      "Nature","Nature Climate Change","Nature Communications","Nature Ecology & Evolution",
      "Nature Energy","Nature Genetics","Nature Human Behaviour","Nature Materials","Nature Methods",
      "Nature Nanotechnology","Nature Physics","Nature Reviews Drug Discovery","Nature Reviews Genetics",
      "Nature Reviews Immunology","Nature Reviews Materials","Nature Reviews Nephrology",
      "Nature Reviews Neurology","Nature Reviews Neuroscience","Nature Reviews Rheumatology",
      "Nature Reviews Urology","Nature Structural & Molecular Biology","Nature Technology",
      "Nature Water","Nature Weather","New Political Economy","NJAS - Wageningen Journal of Life Sciences",
      "Nonlinear Analysis: Real World Applications","North American Journal of Economics and Finance",
      "Oxford Bulletin of Economics and Statistics","Oxford Development Studies","Oxford Economic Papers",
      "Oxford Review of Economic Policy","Pacific Basin Finance Journal","Policy Sciences",
      "Population and Development Review","Portal","Post-Soviet Affairs","Progress in Development Studies",
      "Public Administration and Development","Public Choice","Quantitative Finance",
      "Quarterly Review of Economics and Finance","Real Estate Economics",
      "Regional Science and Urban Economics","Remote Sensing","Research in Social Stratification and Mobility",
      "Resources and Energy Economics","Resources Policy","Review of Development Economics",
      "Review of Economic Dynamics","Review of Environmental Economics and Policy","Review of Finance",
      "Review of Financial Economics","Review of Income and Wealth","Review of Industrial Organization",
      "Review of International Economics","Review of International Political Economy",
      "Review of Quantitative Finance and Accounting","Review of World Economics",
      "Scandinavian Journal of Economics","Scandinavian Journal of Statistics","Science Advances",
      "Science Technology and Human Values","Scientific data","Scottish Journal of Political Economy",
      "Sequential Analysis","Small Business Economics","Social Choice and Welfare","Social Neuroscience",
      "Social Policy and Administration","Society and Natural Resources","Socio-Economic Planning Sciences",
      "Socio-Economic Review","Southern Economic Journal","Statistica Neerlandica","Statistica Sinica",
      "Statistical Journal of the IAOS","Statistics and Computing","Statistics and Probability Letters",
      "Structural Change and Economic Dynamics","Structural Equation Modeling",
      "Studies in Comparative International Development","Sustainable Development",
      "Technological and Economic Development of Economy","Third World Quarterly",
      "Tijdschrift voor Economische en Sociale Geografie","Transportation","Utilities Policy",
      "Venture Capital","Women's Studies International Forum","Work, Employment and Society",
      "World Bank Economic Review","World Bank Research Observer","World Economy",
    ],
  },
  {
    id: "data-science",
    name: "Data Science",
    description: "AI, machine learning, computer vision, NLP, and document analysis conferences and journals. Covers top venues like NeurIPS, ICML, CVPR, ACL, and KDD alongside applied outlets such as Expert Systems with Applications and Pattern Recognition.",
    journals: [
      "AAAI (Association for the Advancement of Artificial Intelligence)",
      "ACM International Conference on Multimedia",
      "ACM Symposium on Document Engineering (DocEng)",
      "Applied Sciences (MDPI)",
      "Association for Computational Linguistics (ACL)",
      "Conference on Computational Collective Intelligence Technologies and Applications (ICCCI)",
      "CoRR","D-Lib Magazine",
      "Digital Image Computing: Techniques and Applications (DICTA)",
      "Electronics",
      "Empirical Methods in Natural Language Processing (EMNLP)",
      "European Conference on Computer Vision (ECCV)",
      "Expert Systems with Applications (Elsevier)",
      "Künstliche Intelligenz","IEEE COMPSAC","IEEE Access",
      "Multimedia Information Processing and Retrieval (MIPR)",
      "IEEE International Conference on Signal Processing (ICSP)",
      "IEEE International Conference on Tools with Artificial Intelligence (ICTAI)",
      "IEEE Transactions on Pattern Analysis and Machine Intelligence (TPAMI)",
      "IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR)",
      "IEEE/CVF Conference on Computer Vision and Pattern Recognition Workshops (CVPRW)",
      "IEEE/CVF International Conference on Computer Vision (ICCV)",
      "IEEE/CVF Winter Conference on Applications of Computer Vision (WACV)",
      "Information Communication Technologies Conference (ICTC)",
      "International Conference on Database Systems for Advanced Applications (DASFAA)",
      "International Conference on Document Analysis and Recognition (ICDAR)",
      "International Conference on Document Analysis and Recognition Workshops (ICDARW)",
      "International Conference on Image Analysis and Processing (ICIAP)",
      "International Conference on Information and Automation for Sustainability",
      "International Conference on Machine Learning (ICML)",
      "International Conference on Machine Learning and Computing (ICMLC)",
      "International Conference on Pattern Recognition (ICPR)",
      "International Conference on World Wide Web (WWW)",
      "International Journal on Document Analysis and Recognition (IJDAR)",
      "International Workshop on Document Analysis Systems (DAS)",
      "International Workshop on Historical Document Imaging and Processing (HIP)",
      "Ivannikov Ispras Open Conference (ISPRAS)",
      "Journal of Imaging",
      "Journal on Information Technologies & Communications",
      "Knowledge-Based Systems",
      "Language Resources and Evaluation Conference (LREC)",
      "Mobile Networks and Applications",
      "NeurIPS (Conference on Neural Information Processing Systems)",
      "North American Chapter of the ACL (NAACL)",
      "Pattern Recognition (Elsevier)","Pattern Recognition Letters",
      "Scientific Data","SIGIR",
      "SIGKDD Conference on Knowledge Discovery and Data Mining (KDD)",
      "SN Computer Science","VISIGRAPP (VISAPP)",
    ],
  },
  {
    id: "education",
    name: "Education",
    description: "Education policy, child development, psychology, and nutrition research. Spans economics of education journals alongside clinical and public health outlets relevant to educational outcomes and human capital formation.",
    journals: [
      "American Economic Journal: Applied Economics","American Economic Journal: Economic Policy",
      "American Economic Review","Annales d'Economie et de Statistique","Annual Review of Psychology",
      "Archives of General Psychiatry","Asia & the Pacific Policy Studies",
      "Asia Pacific Journal of Clinical Nutrition","Asian Development Review","BMJ",
      "British Journal of Educational Psychology","British Journal of Nutrition","Child Development",
      "Children and Youth Services Review","China and World Economy","China Economic Review",
      "Cognitive Processing","Depression and Anxiety","Development and Psychopathology",
      "Developmental Psychology","Developmental Science","Econometrica",
      "Economic Development and Cultural Change","Economic Inquiry","Economic Journal",
      "Economics Letters","Economics of Education Review","Education Finance and Policy",
      "Education Policy Analysis Archives","Experimental Economics","Frontiers in Pediatrics",
      "Frontiers in Pharmacology","Frontiers in Psychology","Frontiers in Public Health",
      "Health Policy and Planning","International Journal of Educational Development",
      "International Journal of Food Sciences and Nutrition","Journal of African Economies",
      "Journal of Alternative and Complementary Medicine","Journal of Child Psychology and Psychiatry",
      "Journal of Computer Assisted Learning","Journal of Development Economics",
      "Journal of Development Effectiveness","Journal of Development Studies",
      "Journal of Economic Perspectives","Journal of Educational Change","Journal of Educational Psychology",
      "Journal of Global Health","Journal of Human Capital","Journal of Human Resources",
      "Journal of Labor Economics","Journal of Political Economy","Journal of Public Economics",
      "Journal of Research on Educational Effectiveness","Journal of the European Economic Association",
      "Lancet","Lancet Global Health","Lancet Infectious Diseases","Lancet Neurology","Lancet Oncology",
      "Lancet Psychiatry","Lancet Public Health","Lancet Regional Health - Americas",
      "Lancet Regional Health - Europe","Malaria Journal","Maternal & Child Nutrition","Nature",
      "Nature Climate Change","Nature Communications","Nature Ecology & Evolution","Nature Energy",
      "Nature Genetics","Nature Human Behaviour","Nature Materials","Nature Methods",
      "Nature Nanotechnology","Nature Physics","Nature Reviews Drug Discovery","Nature Reviews Genetics",
      "Nature Reviews Immunology","Nature Reviews Materials","Nature Reviews Nephrology",
      "Nature Reviews Neurology","Nature Reviews Neuroscience","Nature Reviews Rheumatology",
      "Nature Reviews Urology","Nature Structural & Molecular Biology","Nutrients","Pediatrics",
      "PLOS Medicine","PLOS Neglected Tropical Diseases","PLOS ONE",
      "Proceedings of the National Academy of Sciences of the United States of America",
      "Review of Economics and Statistics","Review of Educational Research",
      "Scandinavian Journal of Economics","Science","Social Science & Medicine",
      "The American Journal of Clinical Nutrition","The American Journal of Tropical Medicine and Hygiene",
      "The Journal of Nutrition","The Lancet","The Lancet Global Health",
      "The Quarterly Journal of Economics","Tropical Medicine and International Health",
      "World Bank Economic Review","World Bank Research Observer","World Development",
    ],
  },
  {
    id: "finance",
    name: "Finance",
    description: "Quantitative finance, financial economics, and AI/ML applications in finance. Includes core finance journals (Journal of Finance, Review of Financial Studies) alongside operations research, optimization, and data mining venues.",
    journals: [
      "AAAI Conference on Artificial Intelligence",
      "ACM International Conference on Web Search and Data Mining",
      "ACM SIGKDD Conference on Knowledge Discovery and Data Mining",
      "ACM Transactions on Intelligent Systems and Technology",
      "ACM Transactions on Knowledge Discovery from Data",
      "Annals of Operations Research","Applied Sciences",
      "Applied Stochastic Models in Business and Industry","Artificial Intelligence",
      "Borsa Istanbul Review","Computational Economics","Computational Optimization and Applications",
      "Conference on Computer Vision and Pattern Recognition",
      "Conference on Empirical Methods in Natural Language Processing",
      "Conference on Neural Information Processing Systems","Data Mining and Knowledge Discovery",
      "Decision Support Systems","Econometrica","Emerging Markets Finance and Trade",
      "European Conference on Machine Learning and Principles and Practice of Knowledge Discovery in Databases",
      "European Journal of Operational Research","Expert Systems with Applications",
      "Finance and Stochastics","Finance Research Letters","Financial Analysts Journal",
      "Financial Management","Foundations and Trends in Finance","IEEE Intelligent Systems",
      "IEEE International Conference on Big Data","IEEE International Conference on Data Mining",
      "IEEE Transactions on Knowledge and Data Engineering",
      "IEEE Transactions on Neural Networks and Learning Systems",
      "Insurance: Mathematics and Economics",
      "International Conference on Artificial Intelligence and Statistics",
      "International Conference on Learning Representations",
      "International Conference on Machine Learning",
      "International Economic Review","International Joint Conference on Artificial Intelligence",
      "International Journal of Data Science and Analytics","International Journal of Finance & Economics",
      "International Journal of Forecasting",
      "International Research Journal of Finance and Economics",
      "International Review of Economics & Finance","International Review of Financial Analysis",
      "Journal of Accounting and Economics","Journal of Alternative Investments",
      "Journal of Applied Mathematics","Journal of Asset Management","Journal of Banking & Finance",
      "Journal of Behavioral and Experimental Finance","Journal of Big Data",
      "Journal of Business & Economic Statistics","Journal of Computational Finance",
      "Journal of Corporate Finance","Journal of Econometrics",
      "Journal of Economic Dynamics and Control","Journal of Empirical Finance","Journal of Finance",
      "Journal of Financial and Quantitative Analysis","Journal of Financial Economics",
      "Journal of Financial Markets","Journal of Financial Stability","Journal of Forecasting",
      "Journal of International Financial Markets Institutions and Money",
      "Journal of Machine Learning Research","Journal of Optimization Theory and Applications",
      "Journal of Pension Economics & Finance","Journal of Portfolio Management","Journal of Risk",
      "Journal of Risk and Financial Management","Knowledge and Information Systems","Machine Learning",
      "Management Science","Manufacturing & Service Operations Management","Mathematical Finance",
      "Mathematical Programming","Mathematics of Operations Research","Neurocomputing",
      "Online Social Networks and Media","Operations Research","Optimization",
      "Pacific-Asia Conference on Knowledge Discovery and Data Mining","Pacific-Basin Finance Journal",
      "Pattern Recognition","PLOS ONE","Quantitative Finance",
      "Research in International Business and Finance","Review of Finance","Review of Financial Studies",
      "SIAM International Conference on Data Mining","SIAM Journal on Numerical Analysis",
      "SIAM Journal on Optimization","Scandinavian Actuarial Journal",
      "Social Network Analysis and Mining",
      "Wiley Interdisciplinary Reviews: Data Mining and Knowledge Discovery",
    ],
  },
  {
    id: "health",
    name: "Health",
    description: "The broadest group, combining clinical medicine, public health, biomedical research, and health economics. Includes top medical journals (NEJM, JAMA, Lancet family, BMJ), Nature Reviews series, and the full economics and statistics corpus for health-adjacent research.",
    journals: [
      "Accounting and Finance","AgBioForum","Agribusiness","Agricultural Economics",
      "Agroecology and Sustainable Food Systems","American Economic Journal: Applied Economics",
      "American Economic Journal: Economic Policy","American Economic Journal: Macroeconomics",
      "American Economic Review","American Journal of Agricultural Economics",
      "American Journal of Bioethics","American Journal of Health Economics",
      "American Journal of Public Health","American Journal of Respiratory and Critical Care Medicine",
      "American Statistician","Annals of Applied Statistics","Annals of Internal Medicine",
      "Annals of Oncology","Annals of Statistics","Annals of Surgery","Annals of the Rheumatic Diseases",
      "Annual Review of Economics","Annual Review of Public Health",
      "Applied Economic Perspectives and Policy","Applied Economics","Applied Economics Letters",
      "Asia Pacific Journal of Management","Asia Pacific Viewpoint","Asia and the Pacific Policy Studies",
      "Asian Development Bank","Asian Development Review","Asian Economic Journal",
      "Asian Economic Papers","Asian Economic Policy Review","Asian-Pacific Economic Literature",
      "Australian Journal of Agricultural and Resource Economics",
      "Australian and New Zealand Journal of Statistics",
      "B.E. Journal of Economic Analysis and Policy","BMC Public Health","BMJ","BMJ Quality & Safety",
      "Biometrical Journal","Biometrika","Biostatistics","Blood","British Journal of Dermatology",
      "Brookings Papers on Economic Activity","CA: A Cancer Journal for Clinicians",
      "Cambridge Journal of Economics","Cambridge Journal of Regions, Economy and Society",
      "Canadian Journal of Economics","Canadian Journal of Statistics","Cancer Cell","Cancer Discovery",
      "Cell","Cell Metabolism","China Economic Review","China Quarterly","China and World Economy",
      "Circulation","Circulation Research","Cities","Clinical Infectious Diseases",
      "Clinical Pharmacology & Therapeutics","Cochrane Database of Systematic Reviews",
      "Communist and Post-Communist Studies","Community Development Journal","Computational Economics",
      "Computational Statistics","Conflict Management and Peace Science","Contemporary Economic Policy",
      "Corporate Social Responsibility and Environmental Management","Development Policy Review",
      "Development and Change","Development in Practice","Diabetes Care","Ecological Economics",
      "Econometric Reviews","Econometric Theory","Econometrica","Economic Development Quarterly",
      "Economic Development and Cultural Change","Economic Geography","Economic History Review",
      "Economic Inquiry","Economic Journal","Economic Modelling","Economic Policy","Economic Record",
      "Economic Systems Research","Economic Theory","Economic and Political Weekly","Economica",
      "Economics Letters","Economics and Politics","Economics of Education Review",
      "Economics of Transition","Economy and Society","Electronic Journal of Statistics",
      "Emerging Markets Finance and Trade","Emerging Markets Review","Empirical Economics",
      "Endocrine Reviews","Energy Economics","Energy Journal","Environment and Development Economics",
      "Environment, Development and Sustainability","Environmental Hazards",
      "Environmental Health Perspectives","Environmental and Ecological Statistics",
      "Environmental and Resource Economics","Eurasian Geography and Economics","Europe-Asia Studies",
      "European Economic Review","European Financial Management","European Heart Journal",
      "European Journal of Development Research","European Journal of Health Economics",
      "European Journal of Political Economy","European Respiratory Journal",
      "European Review of Agricultural Economics","European Urology","Evaluation","Experimental Economics",
      "Explorations in Economic History","Feminist Economics","Finance and Stochastics",
      "Financial Analysts Journal","Financial Management","Financial Review","Fiscal Studies",
      "Food Policy","Food Security","Forest Policy and Economics","Futures",
      "Games and Economic Behavior","Gastroenterology","Gender and Development","Gender and Society",
      "Gender, Technology and Development","Gender, Work and Organization","Gut","Health Affairs",
      "Hepatology","Housing Policy Debate","Housing, Theory and Society","IDS Bulletin",
      "IEEE Geoscience and Remote Sensing Letters",
      "IEEE Journal of Selected Topics in Applied Earth Observations and Remote Sensing",
      "IEEE Transactions on Geoscience and Remote Sensing",
      "ISPRS International Journal of Geo-Information","ISPRS Journal of Photogrammetry and Remote Sensing",
      "Immunity","Implementation Science","Industrial and Corporate Change",
      "Industrial and Labor Relations Review","Information Economics and Policy",
      "Insurance: Mathematics and Economics","Intensive Care Medicine","International Economic Review",
      "International Finance","International Journal of Consumer Studies",
      "International Journal of Educational Development","International Journal of Finance and Economics",
      "International Journal of Game Theory","International Journal of Industrial Organization",
      "International Journal of Market Research","International Journal of Nursing Studies",
      "International Journal of Production Economics","International Journal of Social Economics",
      "International Journal of Urban and Regional Research",
      "International Journal of Water Resources Development",
      "International Review of Economics and Finance","International Review of Financial Analysis",
      "International Review of Law and Economics","International Statistical Review",
      "International Tax and Public Finance","Internet Research","JAMA","JAMA Internal Medicine",
      "JAMA Neurology","JAMA Oncology","JAMA Pediatrics","JAMA Psychiatry","JAMA Surgery",
      "Japan and the World Economy","Journal of Accounting and Economics",
      "Journal of Accounting, Auditing and Finance","Journal of Advanced Transportation",
      "Journal of Agricultural and Resource Economics",
      "Journal of Agricultural, Biological, and Environmental Statistics",
      "Journal of Applied Econometrics","Journal of Applied Economics","Journal of Applied Statistics",
      "Journal of Asian Economics","Journal of Banking and Finance",
      "Journal of Behavioral and Experimental Economics","Journal of Big Data",
      "Journal of Business Finance and Accounting","Journal of Business and Economic Statistics",
      "Journal of Classification","Journal of Clinical Investigation","Journal of Clinical Oncology",
      "Journal of Common Market Studies","Journal of Comparative Economics","Journal of Consumer Affairs",
      "Journal of Consumer Culture","Journal of Consumer Policy","Journal of Consumer Research",
      "Journal of Contemporary China","Journal of Controlled Release","Journal of Corporate Finance",
      "Journal of Cultural Economics","Journal of Cultural Heritage","Journal of Derivatives",
      "Journal of Development Economics","Journal of Development Studies","Journal of Econometrics",
      "Journal of Economic Behavior and Organization",
    ],
  },
];

const CATALOG_STATS = {
  groupCount: JOURNAL_GROUPS.length,
  uniqueJournals: 648,
  totalEntries: JOURNAL_GROUPS.reduce((a, g) => a + g.journals.length, 0),
};

Object.assign(window, { JOURNAL_GROUPS, CATALOG_STATS });
